"""init

Revision ID: 5bafa4072b68
Revises: 
Create Date: 2025-10-19 16:09:34.148390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bafa4072b68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_progress',
    sa.Column('date', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_progress')
    # ### end Alembic commands ###
